### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [kangjihyo/C202309#2]
### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week5/functionMulti
    - Warning: format specifies type 'long' but the argument has type 'int' [line 15]
    - Warning: format specifies type 'long' but the argument has type 'int' [line 16]
    - Warning: format specifies type 'long' but the argument has type 'int' [line 17]
- WARNING in practice/week5/functionHap
    - Warning: return type of 'main' is not 'int' [line 5]

**Comment by kangjihyo** [comment]
해결했습니다.
